---

- name: Ensure Software Collections repos are available
  package: name=centos-release-scl

- name: Ensure HAProxy is installed.
  package: name=rh-haproxy18-haproxy

- name: Ensure HAProxy syspaths are installed.
  package: name=rh-haproxy18-haproxy-syspaths

- name: Symlink HAProxy into /usr/bin  
  file:
    src: /opt/rh/rh-haproxy18/root/usr/sbin/haproxy
    dest: /usr/bin/haproxy
    state: link

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
